package be.unamur.info.b314.compiler.nbc;

import be.unamur.info.b314.compiler.nbc.writer.NBCWriter;
import be.unamur.info.b314.compiler.nbc.writer.PreprocessorWriter;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.OutputStream;
import java.io.PrintWriter;

public class NBCPrinter {
    private final PrintWriter writer;

    public PrintWriter getWriter() { return writer; }

    public NBCPrinter(File file) throws FileNotFoundException {
        this.writer = new PrintWriter(file);
        writeFileHeader();
    }

    public NBCPrinter(String filename) throws  FileNotFoundException {
        this.writer = new PrintWriter(filename);
        writeFileHeader();
    }

    public NBCPrinter(OutputStream stream) {
        this.writer = new PrintWriter(stream);
        writeFileHeader();
    }

    public void flush() {
        this.writer.flush();
    }

    public void close() {
        this.writer.flush();
        this.writer.close();
    }

    private void writeFileHeader() {
        NBCWriter.writeComment(writer, "NBC Program generated by G19");
        PreprocessorWriter.printPreprocessorInclude(writer, "NXTDefs.h");
        PreprocessorWriter.printPreprocessorDefine(writer, "ROT_DEG", "410");
        PreprocessorWriter.printPreprocessorDefine(writer, "FWD_DEG", "1000");
        PreprocessorWriter.printPreprocessorDefine(writer, "SPEED", "80");
        PreprocessorWriter.printPreprocessorDefine(writer, "WAIT", "200");
        PreprocessorWriter.printPreprocessorDefine(writer, "NEAR", "30");
        this.printSoundManagement();
    }

    // TODO To Remove
    public void printDataSegmentStart() {
        this.writer.println("dseg segment");
        this.printEmptyLine();
    }

    // TODO To Remove
    public void printDataSegmentEnd() {
        this.printEmptyLine();
        this.writer.println("dseg ends");
        this.printEmptyLine();
    }

    public void printStructureSegmentStart(String name) { this.writer.format("%s struct", name).println(); }

    public void printStructureSegmentEnd(String name) { this.writer.format("%s ends", name).println(); }

    private void printEmptyLine() {
        this.writer.println();
    }

    private void printSoundManagement() {
        this.printEmptyLine();
        NBCWriter.writeComment(writer,"sound management");
        NBCWriter.writeSegmentStart(writer);
        NBCWriter.writeComment(writer,"definition");
        this.writer.println("SoundPT_def struct");
        this.writer.println("  result sbyte");
        this.writer.println("  freq word");
        this.writer.println("  time word");
        this.writer.println("  loop byte");
        this.writer.println("  vol byte");
        this.writer.println("SoundPT_def ends");
        this.writer.println("SoundGS_def struct");
        this.writer.println("  result byte");
        this.writer.println("  flags byte");
        this.writer.println("SoundGS_def ends");
        this.printEmptyLine();
        NBCWriter.writeComment(writer,"declaration");
        this.writer.println("PT_A SoundPT_def");
        NBCWriter.writeSegmentEnd(writer);
        this.printEmptyLine();
    }
}
