package be.unamur.info.b314.compiler.nbc;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.OutputStream;
import java.io.PrintWriter;

public class NBCPrinter {
    private final PrintWriter writer;

    public NBCPrinter(File file) throws FileNotFoundException {
        this.writer = new PrintWriter(file);
        writeFileHeader();
    }

    public NBCPrinter(String filename) throws  FileNotFoundException {
        this.writer = new PrintWriter(filename);
        writeFileHeader();
    }

    public NBCPrinter(OutputStream stream) {
        this.writer = new PrintWriter(stream);
        writeFileHeader();
    }

    public void flush() {
        this.writer.flush();
    }

    public void close() {
        this.writer.flush();
        this.writer.close();
    }

    private void writeFileHeader() {
        this.printComment("NBC Program generated by G19");
        this.printPreprocessorInclude("NXTDefs.h");
        this.printPreprocessorDefine("ROT_DEG", "410");
        this.printPreprocessorDefine("FWD_DEG", "1000");
        this.printPreprocessorDefine("SPEED", "80");
        this.printPreprocessorDefine("WAIT", "200");
        this.printPreprocessorDefine("NEAR", "30");
    }

    private void printComment(String commnet) {
        this.writer.printf("// %s", commnet).println();
    }

    private void printPreprocessorInclude(String include) {
        this.writer.printf("#include \"%s\"", include).println();
    }

    private void printPreprocessorDefine(String key, String value) {
        this.writer.printf("#define %s %s", key, value).println();
    }
}
